[window]
title = "Terminal"
dynamic_title = false

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold Italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#242933"
foreground = "#D8DEE9"

[colors.normal]
black = "#191D24"
red = "#BF616A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
white = "#BBC3D4"
yellow = "#EBCB8B"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"
